@ADO.NetConnectionOrientedArchitecture_InCore_Example_HostAddress = http://localhost:5092

GET {{ADO.NetConnectionOrientedArchitecture_InCore_Example_HostAddress}}/weatherforecast/
Accept: application/json

###
